"""Build the kernel-level declaration dependency graph for Mathlib4.

Produces ``results/data/stage4v3/decl_graph_raw.jsonl`` — the ground-truth
artifact the entire Lean analysis is built on (~471K declarations, one JSON
object per line, terminated with a ``[DONE]`` sentinel). Each line is

    {"n": <declaration name>, "m": <module>, "d": [<used constants>]}

extracted with the Lean 4 compiler Environment API (``getUsedConstants``),
so an edge means "declaration n's *proof term* uses constant d" — a precise
kernel-level dependency, not a file-level import.

The classical/constructive partition and every depth-from-Classical.choice
computation read this file via ``src/lean/kernel_graph.py``.

Prerequisites
-------------
- A compiled Mathlib4 checkout at ``MATHLIB_PATH`` (see config.py / README;
  override with the MATHLIB_PATH environment variable). Set it up with
  ``scripts/setup_mathlib.sh``.
- Lean 4 + lake on PATH (elan reads the toolchain from the checkout).
- Prebuilt .olean files: ``cd <mathlib4> && lake exe cache get`` (or pass
  ``--fetch-cache`` here).

Resilience
----------
Lean streams JSONL straight to disk, flushing every 5000 declarations, so a
killed run leaves a usable partial file. Re-running resumes from a checkpoint
of already-written names and appends only new entries. ``--force`` restarts
from scratch.

Usage
-----
    python scripts/build_decl_graph.py [--fetch-cache] [--force]

This is a multi-hour run the first time. It is the only step that requires a
working Lean toolchain to *produce* the graph; all downstream Python analysis
only reads the resulting JSONL.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import threading
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
from config import MATHLIB_PATH, DECL_GRAPH_JSONL  # noqa: E402

CHECKPOINT = DECL_GRAPH_JSONL.parent / "decl_checkpoint.txt"
LEAN_SCRIPT_PATH = MATHLIB_PATH / "DumpDeps.lean"

# ---------------------------------------------------------------------------
# Lean extraction script. OUTPATH/CHECKPOINT placeholders are substituted
# before writing. Verbatim from the mathlibmap pipeline that produced the
# graph used in the paper, so the output is bit-for-bit the same schema.
# ---------------------------------------------------------------------------
_LEAN_TEMPLATE = r"""-- DumpDeps.lean  (auto-generated by build_decl_graph.py — do not edit)
import Lean
import Mathlib

open Lean Std

private def jsonStr (s : String) : String :=
  "\"" ++ ((s.replace "\\" "\\\\").replace "\"" "\\\"") ++ "\""

#eval show CoreM Unit from do
  let outPath  : System.FilePath := "OUTPATH_PLACEHOLDER"
  let ckptPath : System.FilePath := "CHECKPOINT_PLACEHOLDER"

  -- Resume support: skip declaration names already written in a prior run.
  let mut done : Std.HashSet String := ∅
  if (← ckptPath.pathExists) then
    let content ← IO.FS.readFile ckptPath
    for n in content.splitOn "\n" do
      if !n.isEmpty then done := done.insert n

  let resuming := !done.isEmpty
  if resuming then
    IO.eprintln s!"[build_decl_graph] Resuming: {done.size} declarations already done."
  else
    IO.eprintln "[build_decl_graph] Starting fresh."

  let env ← getEnv
  IO.eprintln "[build_decl_graph] Iterating constants..."

  let mode := if resuming then IO.FS.Mode.append else IO.FS.Mode.write
  let handle ← IO.FS.Handle.mk outPath mode

  let mut count := 0
  let mut skipped := 0
  for (name, ci) in env.constants do
    if name.isInternal then continue
    let ns := name.toString
    if done.contains ns then
      skipped := skipped + 1
      continue
    let deps : Array Name := match ci with
      | .defnInfo v => v.value.getUsedConstants
      | .thmInfo  v => v.value.getUsedConstants
      | _           => #[]
    let modName : String :=
      match env.getModuleIdxFor? name with
      | some idx => (env.header.moduleNames.getD idx Name.anonymous).toString
      | none => "_"
    let depsFiltered := deps.toList.filter (fun d => !d.isInternal)
    let depsJson := depsFiltered.map (fun d => jsonStr d.toString)
    handle.putStr ("{\"n\":" ++ jsonStr ns ++ ",\"m\":" ++ jsonStr modName ++
                   ",\"d\":[" ++ String.intercalate "," depsJson ++ "]}\n")
    count := count + 1
    if count % 5000 == 0 then
      handle.flush
      IO.eprintln s!"[build_decl_graph] Progress: {count + skipped} processed — {count} new, {skipped} resumed"

  handle.putStr "[DONE]\n"
  handle.flush
  IO.eprintln s!"[build_decl_graph] Complete: {count} new declarations written ({skipped} resumed)."

def main : IO Unit := pure ()
"""


def _write_lean_script() -> None:
    script = _LEAN_TEMPLATE.replace(
        "OUTPATH_PLACEHOLDER", str(DECL_GRAPH_JSONL).replace("\\", "/")
    ).replace(
        "CHECKPOINT_PLACEHOLDER", str(CHECKPOINT).replace("\\", "/")
    )
    LEAN_SCRIPT_PATH.write_text(script, encoding="utf-8")


def _olean_present() -> bool:
    return (MATHLIB_PATH / ".lake" / "build" / "lib").is_dir()


def _raw_is_complete() -> bool:
    if not DECL_GRAPH_JSONL.is_file():
        return False
    try:
        with DECL_GRAPH_JSONL.open("rb") as f:
            f.seek(max(0, DECL_GRAPH_JSONL.stat().st_size - 20))
            return b"[DONE]" in f.read()
    except OSError:
        return False


def _count_raw_lines() -> int:
    if not DECL_GRAPH_JSONL.is_file():
        return 0
    with DECL_GRAPH_JSONL.open(encoding="utf-8", errors="replace") as f:
        return sum(1 for line in f if line.startswith("{"))


def _write_checkpoint() -> int:
    import json
    names: list[str] = []
    with DECL_GRAPH_JSONL.open(encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("{"):
                continue
            try:
                n = json.loads(line).get("n", "")
            except json.JSONDecodeError:
                continue
            if n:
                names.append(n)
    CHECKPOINT.write_text("\n".join(names), encoding="utf-8")
    return len(names)


def _run_lean() -> int:
    _write_lean_script()
    proc = subprocess.Popen(
        ["lake", "env", "lean", "--run", str(LEAN_SCRIPT_PATH)],
        cwd=MATHLIB_PATH, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        text=True, bufsize=1,
    )

    def _forward(pipe):
        for line in pipe:
            print(line, end="", flush=True)

    threads = [threading.Thread(target=_forward, args=(p,), daemon=True)
               for p in (proc.stdout, proc.stderr)]
    for t in threads:
        t.start()
    try:
        proc.wait()
    finally:
        LEAN_SCRIPT_PATH.unlink(missing_ok=True)
    for t in threads:
        t.join(timeout=5)
    return proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fetch-cache", action="store_true",
                    help="Run `lake exe cache get` first if .olean files are missing.")
    ap.add_argument("--force", action="store_true",
                    help="Delete any existing raw file/checkpoint and restart.")
    args = ap.parse_args()

    if not MATHLIB_PATH.is_dir():
        sys.exit(f"Mathlib4 not found at {MATHLIB_PATH}. Run scripts/setup_mathlib.sh "
                 f"or set MATHLIB_PATH.")

    DECL_GRAPH_JSONL.parent.mkdir(parents=True, exist_ok=True)

    if args.force:
        DECL_GRAPH_JSONL.unlink(missing_ok=True)
        CHECKPOINT.unlink(missing_ok=True)
        print("[build_decl_graph] --force: cleared prior raw file and checkpoint.")

    if _raw_is_complete():
        print(f"[build_decl_graph] {DECL_GRAPH_JSONL} already complete "
              f"({_count_raw_lines():,} declarations). Nothing to do.")
        return 0

    if not _olean_present():
        if not args.fetch_cache:
            sys.exit(f".olean cache missing under {MATHLIB_PATH}. Run "
                     f"`lake exe cache get` there, or pass --fetch-cache.")
        print("[build_decl_graph] Fetching .olean cache (lake exe cache get)...")
        if subprocess.run(["lake", "exe", "cache", "get"], cwd=MATHLIB_PATH).returncode:
            sys.exit("lake exe cache get failed.")

    partial = _count_raw_lines()
    if partial:
        n = _write_checkpoint()
        print(f"[build_decl_graph] Resuming from {n:,} existing declarations.")

    rc = _run_lean()
    if rc != 0 or not _raw_is_complete():
        sys.exit(f"Lean run did not complete (exit {rc}, "
                 f"{_count_raw_lines():,} lines so far). Re-run to resume.")
    print(f"[build_decl_graph] Done — {_count_raw_lines():,} declarations -> "
          f"{DECL_GRAPH_JSONL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
